# Generated by Django 3.0.2 on 2020-01-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('desc', models.CharField(max_length=1000)),
                ('icon', models.FileField(upload_to='badge_icons/')),
                ('rarity', models.CharField(choices=[(1, 'Normal'), (2, 'Rare'), (3, 'Super Rare')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('steamid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('communityvisibilitystate', models.BooleanField()),
                ('profilestate', models.BooleanField()),
                ('personaname', models.CharField(max_length=32)),
                ('profileurl', models.URLField(max_length=256)),
                ('avatar', models.URLField(max_length=256)),
                ('commentpermission', models.BooleanField()),
                ('timecreated', models.IntegerField(null=True)),
                ('loccountrycode', models.CharField(max_length=2, null=True)),
                ('API_KEY', models.CharField(max_length=32, null=True)),
                ('badges', models.ManyToManyField(to='core.Badge')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('instanceid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('market_tradable_restriction', models.IntegerField()),
                ('inspect_link', models.URLField(max_length=512, null=True)),
                ('wear', models.CharField(max_length=100)),
                ('float', models.FloatField()),
                ('paintseed', models.IntegerField()),
                ('killeatervalue', models.IntegerField(null=True)),
                ('customname', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('paint_index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('classid', models.IntegerField()),
                ('appid', models.IntegerField()),
                ('tradable', models.BooleanField(default=False)),
                ('icon_url', models.URLField(max_length=512, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('name_color', models.CharField(max_length=7)),
                ('type', models.CharField(max_length=1000)),
                ('rarity', models.CharField(max_length=1000)),
                ('min_float', models.FloatField()),
                ('max_float', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('stickerid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items_give', models.ManyToManyField(related_name='OfferedItems', to='core.ItemInstance')),
                ('items_want', models.ManyToManyField(related_name='WantedItems', to='core.ItemInstance')),
                ('offeror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Gamer')),
            ],
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='item_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ItemType'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='stickers',
            field=models.ManyToManyField(to='core.Stickers'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='inventory',
            field=models.ManyToManyField(to='core.ItemInstance'),
        ),
        migrations.AddField(
            model_name='gamer',
            name='system_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
