# Generated by Django 3.0.2 on 2020-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='tradeurl',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
