# Generated by Django 3.0.2 on 2020-01-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gamer_tradeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='offer_count',
            field=models.IntegerField(default=0),
        ),
    ]
