# Generated by Django 3.0.2 on 2020-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gamer_offer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='max_float',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='min_float',
            field=models.FloatField(null=True),
        ),
    ]
