# Generated by Django 3.0.2 on 2020-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200119_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='float',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='paintseed',
            field=models.IntegerField(null=True),
        ),
    ]
