# Generated by Django 3.0.2 on 2020-01-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200119_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='float',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='inspect_link',
            field=models.URLField(default='http://test.org', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='market_tradable_restriction',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='paintseed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
