# Generated by Django 3.0.2 on 2020-01-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200119_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='API_KEY',
        ),
    ]
