# Generated by Django 3.0.2 on 2020-01-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_gamer_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminstance',
            name='wear',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='wear',
            field=models.CharField(default='Factory-New', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='items_want',
            field=models.ManyToManyField(related_name='WantedItems', to='core.ItemType'),
        ),
    ]
