# Generated by Django 3.0.2 on 2020-01-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200124_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='inventory_2',
            field=models.ManyToManyField(to='core.ItemType'),
        ),
    ]
