# Generated by Django 3.0.2 on 2020-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gamer_inventory_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='confirmed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='offer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
